### ISSUE TITLE
Any possiblity to consider having a 1 large changlog file per keepachangelog.com

### ISSUE THREAD

**Issue by luzpaz** [ASPLes/valvula#2]
Right now all release data is in https://github.com/ASPLes/valvula/tree/master/doc/release-notes and separated per version. Per https://keepachangelog.com it would be easier for downstream package trackers parse a changelog when it's all in one file using the standard. Any interest in doing this ?

**Comment by francisbrosnan** [comment]
Hello @luzpaz,
I've added a ChangeLog (https://github.com/ASPLes/valvula/blob/master/ChangeLog). We will keep that updated with all changes.
Best Regards
